---
#mac_address:            'f8:0f:f9:f0:47:a6'     # Nexus 5
mac_address:            '02:ba:b3:7e:92:e4'     # Pine Phone
ip_address:             '192.168.11.57'
parent:                 'gateway'
notify:                 'no'
pass_users:
  - 'aaron'
