---
# Close enough, but technically, it's an Odroid-HC1, and formerly a Banana Pi M1.
platform:               'raspberry-pi'
#mac_address:            '02:55:08:42:95:49'
mac_address:            '00:1e:06:36:85:6d'
ip_address:             '192.168.11.78'
ssh_unique_port:        '2228'
known_host:             'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQ4ljfsoGCyOFTTYcHSVurAFbJbCxvzpNAUnD1azMNPbV0L9M9xoLOHdPq2CI/h+6SAgorJjvKQ6aQXbQzyj3zX6d0eHQWM/nu08EVyx6zrXQKXkdPnmtqQfN5ifVxn31AM8+qMe0lD9Ce53AJRkzjLFBqYuHa72XqeKONfmGGsIgFelgjR5By0k2cU/WB3UGpGbylVKueBxPTyyC0GkFApQT1bXMkTs6ynRAsxze3amaDsyqL1P/LiI/F9xpG++7yTyG5K7y0BGbsZ3I2wAIouivz0uditWfA+mwMTejDgVsh2GzrCWNHroeRnvlMhUQJD64EwV+njqAEpP0oGkWrmLL703rNrW48gZxPX5HlaSVAC0WhsdKPHWSBdgB8kXT+KZzqlQZ8QUEnBbXJ+5gKfEwp9qyTsHJOpwAgo9mpK02h4EaGbwgypyjmpZZRsvJY05GC5YeY9b0bCfFJR7qZvopTxhO3Iym81szuXQPr9m43/fVICz1eSLPGnGNEN8K1lnRcd0oCqx17+0ic471kzl/BE3SOWUqmOXq69uZSLFRS/G/MCoD9ky57h3HhBONosBgJCCdY5du3HfQ/ez4jOBbWYRRl4n+L4SgCnyBw2Rm64NFljoZKcFTn08CyojvP4ADRaJkEWi3k+lEe5p4sjSoIc12F+PY1FWbtDWCJjw=='
parent:                 "{{ groups['gateway'][0] }}"
notify:                 'yes'
encrypted_storage:
  - name:               'backup'
    backing_device:     '/dev/sda'
    mount_point:        '/backup'
    fstype:             'btrfs'
    mount_options:      'noatime,noauto,nodev,nosuid,noexec,compress=zlib:9'
backup_prefix:          '/backup'
snapshot_yearlies:      '10'
snapshot_monthlies:     '4'
snapshot_dailies:       '4'
snapshot_hourlies:      '4'
reboot_hour:            '10'
reboot_minute:          '59'
update_hour:            '11'
update_minute:          '30'
platform_roles:         'armbian'
