---
# Close enough, but technically, it's an Odroid-HC1, and formerly a Banana Pi M1.
platform:               'raspberry-pi'
#mac_address:            '02:55:08:42:95:49'
mac_address:            '00:1e:06:36:85:6d'
ip_address:             '192.168.11.62'
ssh_unique_port:        '2223'
known_host:             'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDFx6XjY01Z82klAEDoErT1aW4zgHfAx3HNoUJuaCKYp8uwumdhANGuoOSLjDht4AaZZPGhQsLKUfokqBI68Txu+m2EtHAAwEkIc6zaG/Az4hcOZrhPyeJWBb/LbUDj91237Y6hX7TyWlyF0ptH+TzPvvm6QDW/LPONTgLhJRmSJP5Ri3UXUrvSQpQenUAjoiU6CmNrV4uXz7rUUN0qPPpWV2ZftGi2T8itxtHJSV4poCQqyWmb8gNFOnFxKxQTh0nE0yVne6z0sYmHtynjV+Po5MkOiFalnAmaBjTtxab5iQtoKF10x1DuvNi0xhKJynhQVWvPALFPIdmFg+jTaflsb0Jsvm0kA+H+h0gGDUwFsVr6CYch5sEvQ0hDthhGIZMeu/GhhlM9pSudia5GK68qnzgn05arzPq351Vw6kWebsbHYWckAKOhw/1CtAMvQrN09QUTZ7ip9QA3qAGWXoZBtLNYxz4TCl5q1PCLwce0ws2rcekfQXp3+dUm44EDS9a9J2DE/vVL/5Vs/PDryHMj/BRUTxHS6SoZDcqyvSCowhHSti4XU6r7ZVmXZxs6r7+BcBUIQAkFxnvCxrCSs+i7jZ5ePQow/erKQMnqtzB3YbBLNOZYEjXajZdxEuQ6cgNpaw8tb+7YStd4Rp1AQwtxEsvFuTB5M+C+LaIbdoi+jw=='
parent:                 "{{ groups['gateway'][0] }}"
notify:                 'yes'
encrypted_storage:
  - name:               'storage'
    backing_device:     '/dev/sda'
    mount_point:        '/storage'
    fstype:             'ext4'
    mount_options:      'noatime,noauto,nodev,nosuid,noexec'
aliases:
  - 'transmission'
  - 'download'
  - 'convert'
reboot_hour:            '02'
reboot_minute:          '59'
update_hour:            '17'
update_minute:          '00'
backup_hour:            '16'
backup_minute:          '20'
skip_reboot:            False
backup_client_users:
  - 'aaron-phone'
  - 'debian-transmission'
backup_paths:
  aaron-phone:
    - '/storage/aaron-phone'
  debian-transmission:
    - '/var/lib/transmission-daemon'
platform_roles:         'armbian'
