---
mac_address:            '9c:4e:36:c0:d6:00'
ip_address:             '192.168.11.52'
parent:                 'gateway'
notify:                 'no'
ansible_master_user:    'aaron'
update_hour:            '00'
update_minute:          '00'
reboot_hour:            '00'
reboot_minute:          '00'
skip_reboot:            True
backup_users:
  - 'aaron'
