---
mac_address:            '9c:4e:36:c0:d6:00'
netboot_mac_address:    '3c:97:0e:a5:bb:a3'
ip_address:             '192.168.11.52'
parent:                 "{{ groups['gateway'][0] }}"
notify:                 'no'
ansible_master_user:    'aaron'
update_hour:            '00'
update_minute:          '00'
backup_hour:            '04'
backup_minute:          '25'
skip_reboot:            True
backup_client_users:
  - 'aaron'
backup_paths:
  aaron:
    - '/home/aaron/.gnupg'
    - '/home/aaron/.password-store'
    - '/home/aaron/control_center'
    - '/home/aaron/.nethackrc'
    - '/home/aaron/games/dungeons_and_dragons'
pass_users:
  - 'aaron'
