---
#mac_address:            'F0:DE:F1:90:77:CB'  # built-in wifi
mac_address:            '98:48:27:47:69:88'  # USB wifi dongle
ip_address:             '192.168.11.53'
known_host:             'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjtB0AJy4nlj5gZWkXstBbdknzDtKgNXt1t7fDLnfDD9/Q3IyW92kjTF4x+g2e/ShvBYlrxoqxK052s3QV3QHNCn9RNNVpCTeyP4RJzw1dv2gdTrDKWOaNXzHy2RBpi0FQaWgvGZbQO4K9h1TUn/l4OBuyRiAksrOy+eGvhAlfllOj4DusXDLJzO2i9IwVLDrWUVDKqnp5FWE6MOAPcJK2JWl/chAcJxkKFLiBrVN/LgMtBOMDHd2PqsPVp1rTFbuHkGhbEfoBCMQNzES9QNE1PPHrq8EQB8OrEwHaBTSiX1AUJheYAcNpZkmJ2rcqJs7xI3tLR5TEGOeIu6HvEBxp'
parent:                 "{{ gateway }}"
platform:               'laptop'
notify:                 'yes'
aliases:
  - 'remote'
  - 'printer'

reboot_hour:            '01'
reboot_minute:          '29'
update_hour:            '02'
update_minute:          '30'
live_build_minute:      '00'
live_build_hour:        '05'

# Maybe all this Steam and Don't Starve stuff should be in inventory,
# associated with the role, rather than this host.
steamcmd_create_user:   true # create a dedicated user for the steam cmd
steamcmd_user:          steam # owner of the steam cmd
steamcmd_user_home:     /home/{{ steamcmd_user }}/ # home directory of the owner
steamcmd_directory:     /home/{{ steamcmd_user }}/cmd/ # install directory of the cmd
steamcmd_login_timeout: 120

## BEGIN Don't Starve Together dedicated server
# app wide configuration
# No spaces.  This gets used as part of a service name.
game_name:              'Meliora'
game_description:       'Come.'
dst_app_id: 343050
dst_install_dir: '{{ steamcmd_user_home }}apps/dontstarvetogether/'
dst_server_token: 'pds-g^KU_U8IrMGWF^5ejq35my1yKxhNyjjRt3e3Nf8cJ1tnuAvVM6NZ1RGBU='

# world
# Does nothing.  WTF.
#dst_world_preset: SURVIVAL_TOGETHER

# network
dst_server_as_a_service: true
dst_server_name: "{{ game_name }}"
dst_server_description: "{{ game_description }}"
dst_server_intention: social
dst_max_players: 6 # 1..64
dst_pvp: false # true | false
dst_game_mode: survival # endless | survival | wilderness
dst_enable_autosaver: true # creates a save at the start of each day, which will be resumed from when the server restarts
dst_tick_rate: 30 # quality of the server, higher tick rate consumes more bandwidth and CPU
dst_enable_vote_kick: false # vote kick allows users to vote to kick players that are disrupting the game
dst_pause_when_empty: true # pause the simulation when the dedicated server is empty
dst_offline_server: false

# steam

# misc
dst_console_enabled: true

# shard
#dst_shard_is_master: false # Set this in the deployment script.
dst_shard_enable: true # enable different server to work together
dst_shard_name: "{{ game_name }}" # define the shard name
dst_shard_master_ip: "127.0.0.1" # set the master server IP

update_steam_hour: '08'
update_steam_minute: '10'
update_dontstarvetogether_hour: '09'
update_dontstarvetogether_minute: '20'
## END Don't Starve Together dedicated server
