---
platform:               'raspberry-pi'
#mac_address:            'dc:a6:32:5b:62:35' # r-pi wired
mac_address:            'dc:a6:32:5b:62:36' # r-pi wireless
#mac_address:            '98:48:27:51:8c:a1' # USB wifi dongle
#mac_address:            '98:48:27:51:8c:89' # USB wifi dongle
ip_address:             '192.168.11.67'
known_host:             'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIQFUY+hUlCqRVpauutSFmBYpnyD6owCphL122/OqXhPdo2e7dcfp3e6OU3cPWzjUe9PEISRdrS1/o1tdVu4rhyv7ktgrb4f9hrosSZ0EWz9o/fXdv+9ChGsq9gn6IIwh5+TEWQY3CIoUrcj/fk0rQEflequH8YmYsFAzHxQuESPOXY1vKNSMVgF2NkwlnXmUlGnLF9bbT7lbcQDmpHmWMEDo1hanUvb9Q9KFmCBGo7YaeKs1HwQO7x5jwicLZfnYU/vIkmUCq9SqURHZKDIQ+qwqHBg9/xFlcLfOHJl9dhrLCy4PVNX5U/8HjBbDC97IXgRlVMvPLZzmHG+/GMesv/GyrhC9/OtxdCiPhlaEN9xa6BC7zHwuOIW6DwVbbWGvvufv1bhDfQJILnnxlTb82RAi1rqlFRKOBjSyyzWAko3mabY6USTHpE4moHLIFeGUeUXFjPrHXanGHBaGwdp3V9PAoh+UnyBvHgixzOvXxA71b0j+Y+Sl4wHCimkG+XEO5RGahHjMmjFWIjApyqaZLt9zJKbgZ2+91eSzpaUljywcgEuHOS/+8HE+5xIRC8Wq6CKPTiOT6v+shIEgWFXycWPKIFhvIb6jkGRFhRvpiNhNyAHJbxKs1Y88QogjiajcQmCTfkOQO701hLbu3ouX/GV1Kp0CuBWoxz/8uC5tmvw=='
ssh_unique_port:        '2226'
parent:                 "{{ groups['gateway'][0] }}"
notify:                 'yes'
update_hour:            '14'
update_minute:          '17'
#encrypted_storage:
#  - name:               'big_volume'
#    backing_device:     '/dev/mmcblk0p3'
#    mount_point:        '/mnt/big_volume'
#    fstype:             'ext4'
#    mount_options:      'noatime,noauto,nodev,nosuid,noexec'
#motion_mask_file:       'raleigh_front_window.pgm'
platform_roles:         
  - 'raspios'
reboot_hour:            '03'
