---
mac_address:            '74:74:46:c6:81:ff'
ip_address:             '192.168.11.82'
parent:                 "{{ groups['gateway'][0] }}"
notify:                 'no'
pass_users:
  - 'password-store'
