---
platform:               'raspberry-pi'
#mac_address:            'dc:a6:32:5b:62:35' # r-pi wired
mac_address:            'dc:a6:32:5b:62:36' # r-pi wireless
#mac_address:            '98:48:27:51:8c:a1' # USB wifi dongle
#mac_address:            '98:48:27:51:8c:89' # USB wifi dongle
ip_address:             '192.168.11.67'
known_host:             'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCvwCktlkvMcx+dBIFIXTI9Hoz/vX/NTRYbBOW4YBeBR8gkcutZrzOn9mT9MlWARIBL+RmO1ss2VCLb+LE/7t3zBYzVH0cXC+e48ppIoCkXmVZh3YZPzAHiWbp8Q9ocA+xUa1l3nNTPa3N47HuNFejcaPlWZEnC4fN4+aszDwbwLXyTxQrmbLaBK1mOKnibbY8zfTSyu1tT6dpY/+dk1QVjKofhcnZSaZKRSMvMlddrkBNfF0J20SJOlkag19uVRR6NU8gx6pOAoJAuWy0ZeEH6U2ckF+lvgnh5kkGw4N/HawRFnXkBaduXZZ16U+gT4eKgofI3eWOzbb7Ptwg83BmGNSexDXNb9Wb036VisYdcSVxF252WJzsRlystpz6JC9cDG7l9AZ8lsdBtuCw89/4+NsiICvGVwneO7OkxCCiz5pzhasYkh6aVbx2vqtAko4h4Bm8Y5NOdTDcuO9F5pVBrnzALQ0OiwNTrLW9Drfq8WxfsEZGgMRqHvlc7EQnNpCJUM3k/fHT3hbOTSVu6fRuYFaBjI1dzTdaZo58XVU7Kua3PKAmkOuC5meKFwAP3pGA+rVXv+J4x7hioHmWbQg8zJOlrZPGO6s8IhqzVQ9wGQshPskgLBWlx6jJ9kGw30xR5QBlyVSXTXHGlep1b/qHExSxFIYFBxjzBLPmritEz1Q=='
ssh_unique_port:        '2226'
parent:                 "{{ groups['gateway'][0] }}"
notify:                 'yes'
reboot_hour:            '13'
reboot_minute:          '59'
update_hour:            '14'
update_minute:          '17'
#encrypted_storage:
#  - name:               'big_volume'
#    backing_device:     '/dev/mmcblk0p3'
#    mount_point:        '/mnt/big_volume'
#    fstype:             'ext4'
#    mount_options:      'noatime,noauto,nodev,nosuid,noexec'
#motion_mask_file:       'raleigh_front_window.pgm'
aliases:
  - 'remote'
