---
#mac_address:            ''
ip_address:             '45.79.76.174'
parent:                 "{{ isp_gateway }}"
#platform:               ''
notify:                 'yes'
update_hour:            '15'
update_minute:          '30'
reboot_hour:            '14'
reboot_minute:          '59'
