---
mac_address:            'B8:27:EB:47:A1:FB'
ip_address:             '192.168.11.54'
parent:                 "{{ gateway }}"
platform:               'raspberry-pi'
monitor:                'yes'
notify:                 'yes'
e_user:                 'escrow'
aliases:
  - 'ntp'
  - 'wiki'
  - 'public'
  - 'neuronpointer.net'
reboot_hour:            '01'
reboot_minute:          '59'
update_hour:            '02'
update_minute:          '30'
network_interface:      'eth0'
backup_proxy_port:      '2223'
