---
mac_address:            '5C:C5:D4:64:E6:19'
ip_address:             '192.168.11.58'
parent:                 "{{ gateway }}"
platform:               'laptop'
notify:                 'no'
backup_users:
  - 'rachel'
# The vars file in backup_client role can't loop over backup_users.  So there's
# this, which clearly only works as long as we're only doing one user.
backup_user:            'rachel'
update_hour:            ' *'
update_minute:          '30'
reboot_hour:            '00'
reboot_minute:          '00'
skip_reboot:            'yes'
